package sokohuru.muchbeer.king.sokohuruhidescrollbar.activities.settings;

import android.content.Context;
import android.util.Log;
import android.widget.Toast;

/**
 * Created by muchbeer on 6/5/2015.
 */
public class L {

    public static void m(String message) {
        Log.d("SOKO HURU DATABASE", "" + message);
    }

    public static void t(Context context, String message) {
        Toast.makeText(context, message + "", Toast.LENGTH_LONG).show();
    }

    public static void T(Context context, String message) {
        Toast.makeText(context, message + "", Toast.LENGTH_LONG).show();
    }


    public static final String[] MAJIMBO = new String[]{
            "Rorya : STEVEN J OWAWA ",
            "Tarime Mjini : ESTHER N MATIKO",
            "Tarime Vijijini : JOHN HECHE",
            "Musoma Vijijini : ZAKARIA MBULA CHIRAGWILE",
            "Butiama : YUSUPH R KAZI",
            "Bunda Mjini : ESTHER BULAYA",
            "Mwibara :  HARUN D CHIRIKO",
            "Musoma Mjini :  VINCENT J NYERERE",
            "Mwibara :  HARUN D CHIRIKO",
            "Musoma Mjini :  VINCENT J NYERERE",
            "Bunda Vijijini :  SULEIMAN DAUDI Simiyu",
            "Bariadi :  GODWIN SIMBA",
            "Maswa Magharibi :  ABDALA PATEL",
            "Maswa Magharibi :  ABDALA PATEL",
            "Kisesa :  MASANJA MANANI",
            "Meatu :  MESHACK OPULUKWA",
            "Itilima :  MARTINE MAGILE Shinyanga",
            "Msalala :  PAULO MALAIKA",
            "Kahama Mjini :  JAMES LEMBELI",
            "Kahama Vijijini (Ushetu) :  SIMON BUKAKIYE ISAYA",
            "Shinyanga Mjini :  PATROAS PASCHAL K",
            "Kishapu :  FRED T MPENDAZOE Mwanza",
            "Ukerewe :  JOSEPH MKUNDI",
            "Magu :  KALWINZI NGONGOSEKE",
            "Nyamagana :  EZEKIA D. WENJE",
            "Buchosa :  MARTINE KASWAHILI",
            "Sengerema :  HAMIS TABASAMU",
            "Ilemela :  HIGHNESS KIWIA",
            "Misungwi :  LEONIDAS KONDELA Geita",
            "Bukombe :  PROF. KULIKOYELA KAHIGI",
            "Busanda :  ALPHONCE C MAWAZO",
            "Nyang'wale :  GEORGE MABULA",
            "Chato :  DR. BENEDICT LUKANIMA",
            "Mbogwe :  NICODEMUS H MAGANGA",
            "Karagwe :  PRINCE RWAZO",
            "Kyerwa :  BENEDICT MTUNGIREHI",
            "Bukoba Mjini :  WILFRED LWAKATARE",
            "Muleba Kaskazini :  ANSBERT NGURUMO",
            "Muleba Kusini :  ALISTIDES KASHASILA",
            "Biharamulo :  DR. ANTHONY MBASSA Mbeya",
            "Lupa :  NJELU KASAKA",
            "Songwe :  MPOKI MWANKUSYE",
            "Mbeya Mjini :  JOSEPH MBILINYI",
            "Kyela :  ABRAHAM H MWANYAMAKI",
            "Rungwe :  JOHN D MWAMBIGIJA",
            "Busokelo :  BONIPHACE A MWAMUKUSI",
            "Mbozi :  PASCHAL HAONGA",
            "Momba :  DAVID E SILINDE",
            "MBARALI : MODEST KILUFI",
            "Mbeya Vijijini :  ADAM NZELA",
            "Tunduma :  FRANK MWAKAJOKA",
            "Vwawa :  FANUEL MKISI Iringa",
            "Kalenga :  MUSSA L MDEDE",
            "Ismani :  PATRICK OLE SOSOPI",
            "Mufindi Kaskazini :  JUMANNE K MASONDA",
            "Iringa Mjini :  PETER MSIGWA",
            "Kilolo :  BRIAN KIKOTI",
            "Mafinga Mjini :  WILLE MUNGAI Njombe",
            "Njombe Kusini :  EMMANUEL MASONGA",
            "Lupembe (Njombe Kask) :  EDWIN E SWALE",
            "Wanging’ombe :  DISMAS A LUHWAGO",
            "Makete :  JACKSON T MOGELA",
            "Ludewa :  ATHROMEO MKINGA",
            "Makambako :  ORAPH MHEMA Rukwa",
            "Nkasi Kusini :  ALFRED DANIEL SOTOKA",
            "Kwela :  DANIEL NAFTAL NGOGO",
            "Nkasi Kaskazini :  KESSY SOUD",
            "Sumbawanga Mjini :  SADRICK MALILA",
            "Kalambo :  VICTOR MATENI Tanga",
            "Kilindi :  JERADI K MREMA",
            "Muheza :  ERNEST MSINGWA",
            "Korogwe :  AMANI H KIMEA",
            "Korogwe Vijijini :  EMMANUEL KIMEA Kilimanjaro",
            "Rombo :  JOSEPH SELASIN",
            "Same Magharibi :  CHRISTOPHER S MBAJO",
            "Same Mashariki :  NAGENJWA KABOYOKA",
            "Moshi Mjini :  JAFARY P MICHAEL",
            "Hai :  FREEMAN A MBOWE",
            "Siha :  DR. GODWIN MOLLEL Arusha",
            "Arumeru Mashariki :  JOSHUA NASSARI",
            "Arumeru Magharibi :  GIBSON MESIYEKI",
            "Arusha Mjini :  GODBLESS LEMA",
            "Longido :  ONESMO OLE NANGOLE",
            "Monduli :  JULIUS KALANGA",
            "Karatu :  WILLE QAMBALO",
            "Ngorongoro :  ELIAS NGORISA Manyara",
            "Simanjiro :  JAMES KINYASI OLE MILLYA",
            "Mbulu Vijijini :  MIKEL PETRO AWEDA",
            "Hanang :  MAGOMA RASHID DERICK",
            "Babati Mjini :  PAULINE P GEKUL",
            "Babati Vijijini :  LAURENT SURUMBU TARRA",
            "Kiteto :  KIDAWA ATHUMANI IYAVU",
            "Mbulu Mjini :  PAULO HERMAN SULLE Dar es Salaam",
            "Ubungo :  SAED KUBENEA",
            "Kawe :  HALIMA JAMES MDEE",
            "Ukonga :  MWITA MWIKWABE WAITARA",
            "Ilala :  MUSLIM HASSANALI HEIDERALI",
            "Kibamba :  JOHN JOHN MNYIKA",
            "Chalinze :  MATHAYO TM. TORONGEY",
            "Kibaha Mjini :  MICHAEL PAUL MTALY",
            "Kibaha Vijijini :  EDITHA BABBEIYA Morogoro",
            "Mikumi :  JOSEPH HAULE",
            "Morogoro Kusini :  DAVID LUKAGINGIRA",
            "Kilombero :  PETER E LIJUALIKALI",
            "Mlimba :  SUZAN L. KIWANGA",
            "Mvomero :  OSWALD MLAY",
            "Ulanga Magharibi :  ALPHONCE MBASSA",
            "Ulanga Mashariki :  PANCRAS KONGOLI",
            "Morogoro Mjini :  MARCOSSY ALBANIE Dodoma",
            "Kongwa :  ESAU NGOMBEI",
            "Dodoma Mjini :  SINGO BENSON KIGAILA",
            "Bahi :  MATHIAS LYAMUNDA",
            "Chilonwa :  JOHN CHOGONGO Singida",
            "Iramba Magharibi :  JESCA KISHOA",
            "Iramba Mash(Mkalama) :  OSCAR KAPALALE",
            "Singida kaskazini :  DAVID DJUMBE",
            "Singida Mashariki :  TUNDU A LISSU",
            "Singida Magharibi :  MARCO ALLUTE",
            "Manyoni Magharibi :  LUPAA DONALD",
            "Manyoni Mashariki :  ALLUTE EMMANUEL Tabora",
            "Nzega Mjini :  CHARLES MABULA",
            "Igunga :  NG’WIGULU KUBE",
            "Urambo :  SAMWELI NTAKAMLENGA",
            "Ulyankulu :  DEUS KITAPANDYA NGERERE",
            "SIKONGE :  SAID NKUMBA",
            "Manonga :  ALLY KHALFANI NGUZO Katavi",
            "Mpanda Mjini :  JONAS KALINDE",
            "Katavi :  GEORGE SAMBWE",
            "Nsimbo :  GERALD KITABU",
            "Kavuu :  LAURENT SENGA MANGWESHI Kigoma",
            "Kigoma Kaskazini :  DR. YARED FUBUSA",
            "Kigoma Mjini :  DANIEL LUMENYELA Ruvuma",
            "Peramiho :  ELASMO MWINGIRA",
            "Mbinga Magharibi/Nyasa :  CUTHBERT S. NGWATA",
            "Mbinga/Mbinga Vijijini :  EDWIN B AKITANDA",
            "Songea Mjini :  JOSEPH FUIME",
            "Madaba :  EDSON MBOGORO",
          


    };

}
